// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fshobebleamkglzrsgsm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzaG9iZWJsZWFta2dsenJzZ3NtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxNTE5NjcsImV4cCI6MjA2MTcyNzk2N30.6jT47CFNH0y9Oe13BbUmPO6-4ChqRmwKTNjEq0LFMZc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);